---
# .../ansible/scripts/inventory_webhook/config.yaml


testkey1: testval1
testkey2: testval2
application_name: 'Test application'
authentication_token: 5992aa0828f72860a158f88cc7f4179f3c209e2f69b084e0 
